dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: bG8pYNx7mTYhStMQRSIaHgFXzD0jTojjpQgKz5k3oyd4sP7YxgGMl2P+rK2DpBOWYzJABni1s4trcH3LkUv4qamalueCD7ufeLSyFwgZQBU4PtBJg9wyzGQ6+XAeNo61o3y1o7yCwBJNH98BLB2DhnQnJuIA1XAgXu5k3AqWQ851uEP40547EvbVOgwnjPpCCQl5Dk4Uc1w3pnahVeX4nO6Sh7wT2YW5yFOmFCe7lojNdma7l4zVGuYXaK8D35sqizCCq9+iSABP9hlhjQgeHDF9/uPxFCIlDLyKDawjleFTNKp3u+XZbQZ6jMigP+eex0VOOHCsZmENjHk7tcrTjAA9hkbc4wZVDtelhZVpIsTbrZTvhnsmBIve1tE2S1rtcaBvUm9uWQS1WPXlf0PtbsI6MwS4koHuG1FJzZGWZ0E8filuiN9HsahFm/7UFMhcK3E/nVYDMCYA5bCnkF/i38Ib7ykeneDXbzZtuQZXEJ2mfalbR8KMAzPUhe3J7RASpq+2Kq6ON+/KmIoP+8WgCPORDzWfSXcEKlA81pripV30OcCVw1MDc8aqiuqGTrOMepsEZQ+IHCzC3AY9tD+ssRfThnNBc/5lqinC2bCygj28AdjMH+q2gB4Agf7uo6HUd1zjZQ9/vgGU4nm2BI1g8yuytpixDGwwhhOFX40snkA=
